<?php
namespace Test;

require __DIR__ . '/../vendor/autoload.php';

use logan8920\IOCommentParser\IOCommentParser;

class Test
{
    public function run()  {
        
        $data = '{
   "id": 65332,
   "user_id": "20220427",
   "company_id": 10,
   "company_type": null,
   "partner_id": 1,
   "ac_no": null,
   "account_type": null,
   "customer_name": "",
   "dob": null,
   "contact_number": 9913734694,
   "rm_number": null,
   "additional_contact_number": "",
   "landline": null,
   "retailer_id": "",
   "retailer_name": null,
   "address": "Alpana provijen store,Kodyar nager,Prkash stil,New v I p rod,VADODARA,Gujarat,390022,VADODARA,Gujarat,390022",
   "address_landmark": null,
   "city": "VADODARA",
   "state": "Gujarat",
   "pincode": 390022,
   "landmark": "",
   "asm": "ACWGJ1BRCVAD01",
   "retailer": null,
   "distributor": null,
   "sh_username": "CHCWGJ1BRC0001",
   "sh_name": "SOLANKI KEYURKUMAR RASIKBHAI",
   "rh_username": "SHCWGJ00000001",
   "rh_name": "HASMUKH THAKOR",
   "zh_username": "RHWEWT00000001",
   "zh_name": "ROHAN CHOUDHARY",
   "finding": null,
   "board_sighted": null,
   "io_comment": null,
   "person_available_name": null,
   "age_person_available": null,
   "relation_person_available": null,
   "specify_relation": null,
   "relation_detail": null,
   "person_availabilty": null,
   "reason_for_no_availability": null,
   "customer_reaction": null,
   "idle_status": null,
   "type_of_setup": null,
   "premise_area": null,
   "pic1": null,
   "pic2": null,
   "pic3": null,
   "pic4": null,
   "pic5": null,
   "pic6": null,
   "pic7": null,
   "call_response": null,
   "call_remarks": null,
   "premise_type": null,
   "monthly_rent": null,
   "office_type": null,
   "nature_of_business": null,
   "other_business": null,
   "stock_seen": null,
   "duartion_occupancy": null,
   "premise_size": null,
   "emp_strength": null,
   "no_emp_seen": null,
   "other_details": null,
   "complaints": null,
   "complaints_details": null,
   "customer_enquiry": null,
   "customer_known": null,
   "customer_emp_details": null,
   "emp_designation": null,
   "company_name": null,
   "checker_name": null,
   "sign_agent": null,
   "sign_checker": null,
   "opinon": null,
   "contacted_person_discussion": null,
   "occupancy_rented": null,
   "occ_rent_expiry_date": null,
   "aadhar_number": "",
   "aadhar_details": "",
   "fv_status": "negative",
   "fv_negative_reason": null,
   "customer_pic": null,
   "merchant_pic": null,
   "pdf": null,
   "source_name": null,
   "source_email": null,
   "refno": "4eff9e68-e4e7-4813-b55c-50b23010c3a5",
   "merchant_name": "BARIYA ALPNABEN",
   "merchant_dba_name": "Alpana provijen store",
   "mcc_code": 0,
   "mcc_desc": "",
   "final_remark": "-",
   "field_visit_time": "",
   "additional_info": "-",
   "region": "",
   "num_of_yrs": null,
   "level_of_stock": null,
   "mswipe_terminal_seen": null,
   "mswipe_not_seen_reason": null,
   "merchant_neighbour_name": null,
   "merchant_neighbour_feedback": null,
   "business_board_seen": null,
   "name_plate": null,
   "source_lat": null,
   "source_lng": null,
   "gist_of_disc": null,
   "residence_type": null,
   "ownership_type": null,
   "residence_stability": null,
   "locality": null,
   "negative_area": null,
   "third_party_confirmation": null,
   "relationship_applicant": null,
   "verification_status": null,
   "untraceable_reason": null,
   "mid": null,
   "merchantUpiId": null,
   "DeviceID": null,
   "SimNo": null,
   "BankName": null,
   "soundbox_fields": null,
   "dmi_fields": null,
   "co_borrow": null,
   "co_borrow_1_details": null,
   "co_borrow_2_details": null,
   "guarantor": null,
   "guarantor_1_details": null,
   "guarantor_2_details": null,
   "auto_gen_io_comment": null,
   "bharatpe_fields": null,
   "iti_fields": null,
   "easebuzz_fields": null,
   "status": 2,
   "gps_location": null,
   "latitude": null,
   "longitude": null,
   "file_lat": null,
   "file_lng": null,
   "addeddate": "2025-12-01 13:53:08",
   "dateadded": null,
   "cpv_address": null,
   "lastupdated": "2025-12-01 13:53:08",
   "completed_by": null,
   "reattempt": null
 }';
        $company = "Paytm";
        
        $result = IOCommentParser::setData($data,$company)->makeIOComment()->getComment();
        
        print_r($result);
        
    }
    
}


$test = new Test();
$test->run();


